[package]
name = "nanachi-mir"
description = "MIR (control flow graph) for nanachi-lang"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
nanachi-ast = { workspace = true }
nanachi-hir = { workspace = true }
nanachi-lexer = { workspace = true }

[dev-dependencies]
nanachi-parser = { workspace = true }
